---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: News
- type: jekyll-posts
  label: News
  create: all
  new_doc_ext: markdown
  templates:
  - release
- type: heading
  label: Documentation
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: docs/_docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: docs/_tutorials
  label: Tutorials
  create: all
  match: "**/*"
upload_dir: docs/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: docs/_site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
